Repository ca-cwds/perry, pull requests merged in 2019-01, with the labels that each got.

#288 Added the label checker and removed release parameters
  Jenkinsfile-pull-request.groovy
Labels: patch

#289 COG-1011_COG-1081 View Workers phone number in CWS-CARES
  config/idm.groovy
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
  src/test/resources/fixtures/idm/get-user/state-admin-by-super-admin.json
  src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-invalid-county-in-cognito.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
  src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
  src/test/resources/fixtures/idm/get-users/all-valid.json
  src/test/resources/fixtures/idm/users-search/valid.json
  src/test/resources/fixtures/idm/verify-user/verify-valid.json
Labels: enhancement, minor

#293 Fit 372 sem ver for perry
  build.gradle
Labels: patch

#294 Changed projectVersion to String for SemVer purpose
  build.gradle
Labels: patch

#295 FIT 372 SemVer For Perry
  Jenkinsfile-complete.groovy
Labels: minor

#296 Clean up and added the stage for deploying to pre-int and Integration
  Jenkinsfile-complete.groovy
Labels: patch

#298 COG-1082 Worker Phone Number Logic Implementation
  config/idm.groovy
  src/main/java/gov/ca/cwds/data/converter/StringToRequiredIntegerConverter.java
  src/main/java/gov/ca/cwds/data/converter/StringToRequiredLongConverter.java
  src/main/java/gov/ca/cwds/data/persistence/auth/StaffPerson.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/test/java/gov/ca/cwds/data/converter/StringToRequiredLongConverterTest.java
  src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
  src/test/resources/fixtures/idm/get-user/state-admin-by-super-admin.json
  src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-invalid-county-in-cognito.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
  src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
  src/test/resources/fixtures/idm/get-users/all-valid.json
  src/test/resources/fixtures/idm/users-search/valid.json
  src/test/resources/fixtures/idm/verify-user/verify-valid.json
Labels: minor

#299 Fix for failure notification
  Jenkinsfile-complete.groovy
  Jenkinsfile-pull-request.groovy
Labels: patch

#297 COG 1072 User Created Change Log Record
  config/perry-dev.yml
  config/perry-prod.yml
  src/main/java/gov/ca/cwds/PerryApplication.java
  src/main/java/gov/ca/cwds/config/SpringAsyncConfiguration.java
  src/main/java/gov/ca/cwds/idm/dto/AuditEvent.java
  src/main/java/gov/ca/cwds/idm/dto/UserChangeLogRecord.java
  src/main/java/gov/ca/cwds/idm/event/ChangeLogEventListener.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/exception/ChangeLogListenerExceptionHandler.java
  src/main/java/gov/ca/cwds/idm/service/AuditLogService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/IndexRestSender.java
  src/main/java/gov/ca/cwds/idm/service/SearchService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/AuditProperties.java
  src/main/java/gov/ca/cwds/idm/service/retry/IndexRetryConfiguration.java
  src/main/java/gov/ca/cwds/util/AuditLogsUtil.java
  src/main/java/gov/ca/cwds/util/CurrentAuthenticatedUserUtil.java
  src/main/java/gov/ca/cwds/util/UniversalUserTokenDeserializer.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/SearchServiceTest.java
  src/test/java/gov/ca/cwds/service/UniversalUserTokenDeserializerTest.java
  src/test/java/gov/ca/cwds/util/AuditLogsUtilTest.java
Labels: minor

#302 rearranged the SemVer label check
  Jenkinsfile-pull-request.groovy
Labels: patch

#303 COG-1097 changed audit event datetime format to adhere unified pattern
  src/main/java/gov/ca/cwds/idm/dto/AuditEvent.java
Labels: patch

#304 COG-1075 Edit Workers phone number in Cognito
  config/idm.groovy
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/dto/UserUpdate.java
  src/main/java/gov/ca/cwds/idm/dto/UsersSearchCriteria.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/AttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/AttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CollectionAttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CustomUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/StandardUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/StringAttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/dto/CognitoUsersSearchCriteria.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoPhoneConverter.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUsersSearchCriteriaUtil.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
  src/main/java/gov/ca/cwds/idm/service/validation/PhoneNumberValidator.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/AttributesBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoPhoneConverterTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUsersSearchCriteriaUtilTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtilsTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/PhoneNumberValidatorTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/java/gov/ca/cwds/idm/util/TestUtils.java
  src/test/java/gov/ca/cwds/util/UtilsTest.java
  src/test/resources/fixtures/idm/update-user/invalid-phone-number.json
Labels: minor

#305 COG-1097 User's Role Changed Changelog Record
  src/main/java/gov/ca/cwds/config/api/idm/Roles.java
  src/main/java/gov/ca/cwds/idm/dto/UserChangeLogRecord.java
  src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
  src/main/java/gov/ca/cwds/idm/event/ChangeLogEventListener.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/main/java/gov/ca/cwds/idm/service/AuditLogService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/util/AuditLogsUtil.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: minor

#307 COG-1097 Sonar bug fix
  src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
Labels: patch

#308 COG-1095 Permissions changed event
  src/main/java/gov/ca/cwds/config/api/idm/Roles.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserAttributeChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/AttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CollectionAttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/StringAttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/AbstractUserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/CollectionAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/CollectionUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/RoleAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/RolesUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
  src/test/java/gov/ca/cwds/idm/RolesTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/AttributesBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtilsTest.java
Labels: minor

#309 COG-1099 Email Changed Event
  src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/AbstractUserAttributeDiffBuilder.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
Labels: minor

#310 COG-1099 Event types renaming, transforming role_id to role_name for admin
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
Labels: patch

#311 COG-1099 event type renaming
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
Labels: patch

#312 COG-1096 Accout Status Changed Event
  src/main/java/gov/ca/cwds/config/api/idm/Roles.java
  src/main/java/gov/ca/cwds/idm/dto/UserEnableStatusRequest.java
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserAttributeChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/OtherUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/AbstractUserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/CollectionAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/CollectionUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/EmailUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/RoleAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/RolesUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserEnabledStatusAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/AbstractUserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/CollectionAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/EmailAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/RoleAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/StringAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/UserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/UserEnabledStatusDiffBuilder.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilderTest.java
Labels: minor

#314 COG-1096 minor fixes
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/Permission.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/util/IdToNameConverter.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: patch

#315 COG-1096 renamed old and new value for Account Status Changed event
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
Labels: patch

#318 Hotfix pipeline
  Jenkinsfile-hotfix.groovy
Labels: patch

#317 COG-1160 Add possibility to update User.notes field
  build.gradle
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/dto/UserUpdate.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserAttributeChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/MappingService.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseDiffMapBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/Diff.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/NsUserBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseDiffMapBuilderTest.java
  src/test/java/gov/ca/cwds/rest/api/SystemInformationResourceTest.java
  src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
  src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
  src/test/resources/fixtures/idm/get-users/all-valid.json
  src/test/resources/fixtures/idm/get-users/search-valid.json
  src/test/resources/liquibase/ns-data.xml
Labels: minor

#319 COG-1079 cleaned up resent registration date/time
  src/main/java/gov/ca/cwds/idm/dto/RegistrationResubmitResponse.java
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/MappingService.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
  src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
  src/test/resources/fixtures/idm/get-user/state-admin-by-super-admin.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
  src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-racfid-valid-2.json
  src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
  src/test/resources/fixtures/idm/get-users/all-valid.json
  src/test/resources/fixtures/idm/users-search/valid.json
  src/test/resources/fixtures/idm/users-search/yolod.json
  src/test/resources/liquibase/ns-data.xml
Labels: minor

#316 Update change log text for brevity and clarity
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
Labels: patch

#321 COG-1079 removed last_registration_resubmit_time from user table
  build.gradle
Labels: patch
