Repository ca-cwds/perry, pull requests merged in 2019-03, with the labels that each got.

#354 COG-1228 change log events refactoring
  src/main/java/gov/ca/cwds/idm/service/AuditEventIndexService.java
  src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithUserLogTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
Labels: patch

#355 Locked field fix
  config/idm.groovy
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CustomUserAttribute.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
Labels: patch

#351 COG-1164: Unlock Service Implementation
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/lifecycle/UserLockService.java
  src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationService.java
  src/main/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserLockStatus.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoRequestHelper.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationService.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
  src/test/java/gov/ca/cwds/idm/UserLockTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
  src/test/resources/fixtures/idm/user-lock-status/unlock-user-error.json
  src/test/resources/fixtures/idm/user-lock-status/unlock-user-with-different-county.json
Labels: minor

#353 COG-1266 Account Lockout Notification Web Service
  src/main/java/gov/ca/cwds/config/api/idm/IdmBasicAuthenticationProvider.java
  src/main/java/gov/ca/cwds/config/api/idm/PerryIdmConfiguration.java
  src/main/java/gov/ca/cwds/config/api/idm/Roles.java
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/IdmRestExceptionHandler.java
  src/main/java/gov/ca/cwds/idm/dto/IdmNotification.java
  src/main/java/gov/ca/cwds/idm/dto/UserChangeLogRecord.java
  src/main/java/gov/ca/cwds/idm/event/AdminCausedChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/NotesChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/SystemCausedChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserLockedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserLoggedInEventListener.java
  src/main/java/gov/ca/cwds/idm/event/UserRegistrationResentEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/main/java/gov/ca/cwds/idm/exception/OperationNotSupportedException.java
  src/main/java/gov/ca/cwds/idm/service/IdmService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/authorization/UserRolesService.java
  src/main/java/gov/ca/cwds/idm/service/exception/ExceptionFactory.java
  src/main/java/gov/ca/cwds/idm/service/notification/NotificationTypes.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/IdmNotificationTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/authorization/UserRolesServiceTest.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
Labels: minor

#356 COG-1164: Changed the locked value from 0/1 to false/true
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserLockStatus.java
Labels: patch

#352 COG-1147 New user phone and extension validation rules for update operation
  src/main/java/gov/ca/cwds/idm/service/NsUserBuilder.java
  src/main/java/gov/ca/cwds/idm/service/validation/PatternValidator.java
  src/main/java/gov/ca/cwds/idm/service/validation/PhoneNumberValidator.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/BasePatternTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/PhoneExtensionPatternTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/PhoneNumberPatternTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/PhoneNumberValidatorTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
  src/test/java/gov/ca/cwds/util/UtilsTest.java
  src/test/resources/fixtures/idm/update-user/clear-phone-number.json
  src/test/resources/fixtures/idm/update-user/invalid-phone-extension.json
  src/test/resources/fixtures/idm/update-user/invalid-phone-number.json
Labels: patch

#357 COG-1266 swagger notes and statuses groomed
  src/main/java/gov/ca/cwds/idm/IdmResource.java
Labels: patch

#358 COG-1179: Account Unlockout actions recorded in Change Log
  src/main/java/gov/ca/cwds/idm/event/UserUnlockedEvent.java
  src/main/java/gov/ca/cwds/idm/lifecycle/UserLockService.java
  src/test/java/gov/ca/cwds/idm/UserLockTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: minor

#360 COG-1164: Unlock service implementation
  src/main/java/gov/ca/cwds/idm/lifecycle/UserLockService.java
  src/test/java/gov/ca/cwds/idm/UserLockTest.java
Labels: minor

#359 COG-1261: User saved in Cognito is not removed if error occurs at saving user to database
  src/main/java/gov/ca/cwds/config/TokenServiceConfiguration.java
  src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/resources/fixtures/idm/create-user/db-fail.json
Labels: bug, minor

#361 COG-1164: Reset MAX_LOGIN_ATTEMPTS to "0" after unlocking user
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CustomUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoRequestHelper.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
Labels: minor

#362 COG-1266 persisting the locked event without sending it to dora
  src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/test/java/gov/ca/cwds/idm/IdmNotificationTest.java
Labels: bug, patch

#363 FIX: credentials updated for integration tests
  Jenkinsfile-complete.groovy
  Jenkinsfile-hotfix.groovy
  Jenkinsfile-integration-test.groovy
Labels: patch

#364 COG-1263 User successfully updated in Cognito when error occurs at updating user in database
  src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/resources/fixtures/idm/update-user/cognito-update-attrs-fail.json
  src/test/resources/fixtures/idm/update-user/ns-db-update-fail.json
Labels: bug, minor

#365 Cog-1147 New phone validation rule
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/service/validation/PhoneNumberPatternTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
  src/test/resources/fixtures/idm/update-user/invalid-phone-number.json
Labels: patch

#345 WIP COG-1117 Implement user retrieving approach reading data from Postgres DB
  .gitignore
  build.gradle
  config/idm.groovy
  src/main/java/gov/ca/cwds/data/persistence/auth/CwsOffice.java
  src/main/java/gov/ca/cwds/idm/exception/UserNotFoundException.java
  src/main/java/gov/ca/cwds/idm/service/MappingService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/exception/ExceptionFactory.java
  src/main/java/gov/ca/cwds/idm/service/mapper/NsUserMapper.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/java/gov/ca/cwds/service/scripts/IdmMappingScript.java
  src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/GetUserTest.java
  src/test/java/gov/ca/cwds/idm/IdmNotificationTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/mapper/NsUserMapperTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/java/gov/ca/cwds/idm/util/TestUtils.java
  src/test/java/gov/ca/cwds/service/scripts/IdmMappingScriptTest.java
  src/test/resources/fixtures/idm/get-user/absent-in-idm.json
  src/test/resources/fixtures/idm/get-user/absent-in-ns-db.json
  src/test/resources/fixtures/idm/get-user/locked-user.json
  src/test/resources/fixtures/idm/get-user/no-locked-value-unlocked.json
  src/test/resources/fixtures/idm/get-user/state-admin-by-super-admin.json
  src/test/resources/fixtures/idm/get-user/super-admin.json
  src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-cws-staff-privs.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-invalid-county-in-cognito.json
  src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
  src/test/resources/fixtures/idm/users-search/valid.json
  src/test/resources/liquibase/ns-data.xml
Labels: major

#366 FIT-485 fix critical code smells.
  src/main/java/gov/ca/cwds/UniversalUserToken.java
  src/main/java/gov/ca/cwds/config/Constants.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/StaffAuthorityPrivilege.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/StaffUnitAuthority.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/UserAuthorization.java
  src/main/java/gov/ca/cwds/service/mfa/model/AuthParameters.java
  src/main/java/gov/ca/cwds/service/mfa/model/AuthenticationResult.java
  src/main/java/gov/ca/cwds/service/sso/custom/form/FormService.java
Labels: patch

#369 FIX: idm script bug fix when nsUser is absent in NS DB
  src/main/java/gov/ca/cwds/idm/service/UserService.java
Labels: bug, patch

#367 Fit 486 fix perry major code smells
  api-security/src/main/java/gov/ca/cwds/security/module/SecurityModule.java
  api-security/src/main/java/gov/ca/cwds/security/permission/AbacPermission.java
  api-security/src/main/java/gov/ca/cwds/security/utils/Utils.java
  src/main/java/gov/ca/cwds/config/RedisConfiguration.java
  src/main/java/gov/ca/cwds/config/logging/DebugRestTemplateInterceptor.java
  src/main/java/gov/ca/cwds/data/persistence/auth/AssignmentUnit.java
  src/main/java/gov/ca/cwds/data/persistence/auth/CmsUserAuthPrivilege.java
  src/main/java/gov/ca/cwds/data/persistence/auth/CwsOffice.java
  src/main/java/gov/ca/cwds/data/persistence/auth/StaffAuthorityPrivilege.java
  src/main/java/gov/ca/cwds/idm/service/notification/NotificationTypes.java
  src/main/java/gov/ca/cwds/rest/api/LoginResource.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/UserAuthorization.java
  src/main/java/gov/ca/cwds/service/scripts/Script.java
  src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
  src/main/java/gov/ca/cwds/service/sso/PerryUserInfoTokenService.java
  src/main/java/gov/ca/cwds/service/sso/UniversalUserTokenExtractor.java
  src/main/java/gov/ca/cwds/service/sso/custom/cognito/CognitoSsoService.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/test/java/gov/ca/cwds/smoketest/SmokeTest.java
Labels: patch

#370 fix application failure to start
  src/main/java/gov/ca/cwds/config/RedisConfiguration.java
Labels: patch

#349 COG-1255 Refactor "Search by list of RACFIDs" service to use PostgresDB as a primary source of User data
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
  src/main/java/gov/ca/cwds/idm/service/IdmService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/test/java/gov/ca/cwds/idm/SearchUsersTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/resources/fixtures/idm/get-user/locked-user.json
  src/test/resources/fixtures/idm/get-user/no-locked-value-unlocked.json
  src/test/resources/fixtures/idm/get-user/unlocked_user.json
  src/test/resources/fixtures/idm/users-search/valid.json
  src/test/resources/fixtures/idm/users-search/yolod.json
  src/test/resources/liquibase/ns-data.xml
Labels: minor

#368 WIP Cog-1302 authorization uses postgres dp
  .gitignore
  build.gradle
  config/cognito.groovy
  config/idp.groovy
  config/perry-prod.yml
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/service/scripts/IdpMappingScript.java
  src/main/java/gov/ca/cwds/service/sso/UniversalUserTokenExtractor.java
  src/test/java/gov/ca/cwds/idm/LastLoginTimeTest.java
  src/test/java/gov/ca/cwds/service/scripts/CognitoMappingScriptTest.java
  src/test/java/gov/ca/cwds/service/scripts/DefaultMappingCalsTest.java
  src/test/java/gov/ca/cwds/service/scripts/DefaultMappingTest.java
  src/test/java/gov/ca/cwds/service/scripts/IdmMappingScriptTest.java
  src/test/java/gov/ca/cwds/service/scripts/IdpMappingScriptTest.java
  src/test/java/gov/ca/cwds/service/scripts/UniversalUserTokenExtractorTest.java
  src/test/java/gov/ca/cwds/web/MockOAuth2Service.java
  src/test/java/gov/ca/cwds/web/PerryMFALoginTest.java
  src/test/resources/fixtures/mfa/mfa-response-key-info-missing.json
  src/test/resources/fixtures/mfa/mfa-response-missing-racfid.json
  src/test/resources/fixtures/mfa/mfa-response.json
  src/test/resources/scripts/cognito/cognito-no-roles.json
  src/test/resources/scripts/cognito/cognito.groovy
  src/test/resources/scripts/cognito/cognito.json
  src/test/resources/scripts/default/default.groovy
Labels: minor

#373 COG-1302: NsUser servicies fix
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
Labels: patch

#374 19.5 fi2
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/exception/ExceptionFactory.java
Labels: bug, patch

#376 COG-1302: Serializable is added to NS entities
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/Permission.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/UserLog.java
Labels: patch

#375 COG-1297 Account Lockout change log event does not have user_name and user_role values
  src/main/java/gov/ca/cwds/idm/event/SystemCausedChangeLogEvent.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: patch

#377 COG-1306 AuditEvents Job to Grab Only Failed and Specific Events While Run
  build.gradle
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsAuditEvent.java
  src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
  src/test/java/gov/ca/cwds/idm/persistence/ns/repository/NsAuditEventRepositoryTest.java
  src/test/java/gov/ca/cwds/idm/service/AuditEventServiceTest.java
Labels: minor

#372 COG-1254 change createUser and updateUser to use only PostgresDB
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsUserRepository.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/CustomUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/StandardUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtil.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
  src/main/java/gov/ca/cwds/idm/service/diff/UpdateDifference.java
  src/main/java/gov/ca/cwds/idm/service/exception/ExceptionFactory.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtilTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtilsTest.java
  src/test/java/gov/ca/cwds/idm/service/diff/DifferencingTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
Labels: minor

#378 FIT-486 fix major code smells.
  src/main/java/gov/ca/cwds/UniversalUserToken.java
  src/main/java/gov/ca/cwds/config/Constants.java
  src/main/java/gov/ca/cwds/config/api/common/SpApiAuthenticationProvider.java
  src/main/java/gov/ca/cwds/config/logging/DebugRestTemplateInterceptor.java
  src/main/java/gov/ca/cwds/config/mfa/MfaAuthenticationProvider.java
  src/main/java/gov/ca/cwds/data/persistence/auth/StaffUnitAuthority.java
  src/main/java/gov/ca/cwds/data/reissue/TokenRepository.java
  src/main/java/gov/ca/cwds/data/reissue/model/PerryTokenEntity.java
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/AuditProperties.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CommonDoraProperties.java
  src/main/java/gov/ca/cwds/idm/service/cognito/SearchProperties.java
  src/main/java/gov/ca/cwds/idm/service/notification/NotificationTypes.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/AuthPrivilege.java
  src/main/java/gov/ca/cwds/rest/api/domain/auth/GovernmentEntityType.java
  src/main/java/gov/ca/cwds/service/IdentityMappingService.java
  src/main/java/gov/ca/cwds/service/mfa/CognitoResponseService.java
  src/main/java/gov/ca/cwds/service/sso/custom/cognito/CognitoLogoutUrlProvider.java
  src/main/java/gov/ca/cwds/service/sso/custom/form/DevAuthenticationProvider.java
  src/main/java/gov/ca/cwds/service/sso/custom/saf/SAFLogoutUrlProvider.java
  src/main/java/gov/ca/cwds/smoketest/JwtCheck.java
  src/main/java/gov/ca/cwds/web/PerryLogoutSuccessHandler.java
  src/main/java/gov/ca/cwds/web/error/AuthenticationEventListener.java
Labels: patch

#371 Return the new email address when duplication errors are thrown
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
Labels: bug, patch

#379 COG-1302: sets are copied to avoid NSUser serialization to session
  config/cognito.groovy
Labels: patch

#381 COG-1273: CALS-admin role removing
  src/main/java/gov/ca/cwds/config/api/idm/PerryIdmAdminConfiguration.java
  src/main/java/gov/ca/cwds/config/api/idm/PerryIdmConfiguration.java
  src/main/java/gov/ca/cwds/config/api/idm/Roles.java
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/service/authorization/UserRolesService.java
  src/main/java/gov/ca/cwds/idm/service/filter/MainRoleFilter.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/AbstractAdminActionsAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/AdminRoleImplementorFactory.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminRoleImplementor.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/SuperAdminRoleImplementor.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/GetUserTest.java
  src/test/java/gov/ca/cwds/idm/GetUsersTest.java
  src/test/java/gov/ca/cwds/idm/OfficesTest.java
  src/test/java/gov/ca/cwds/idm/PermissionsTest.java
  src/test/java/gov/ca/cwds/idm/RolesTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/VerifyUserTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/AuditEventServiceTest.java
  src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/authorization/UserRolesServiceTest.java
  src/test/java/gov/ca/cwds/idm/service/filter/MainRoleFilterTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/CalsAdminRoleImplementorTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/StateAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/SuperAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/SuperAdminRoleImplementorTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
  src/test/resources/fixtures/idm/get-user/state-admin-by-super-admin.json
  src/test/resources/fixtures/idm/get-user/super-admin.json
  src/test/resources/fixtures/idm/roles/valid.json
Labels: minor

#383 COG-1273: data-model version is updated
  build.gradle
Labels: minor

#382 FIT-366 Apply the new shared library for smoke testing to Perry
  Jenkinsfile-complete.groovy
  Jenkinsfile-release.groovy
  build.gradle
  docker/DockerfileIntegrationTest
  docker/DockerfileIntegrationTestDev
  integration-tests/build.gradle
  integration-tests/src/test/java/gov/ca/cwds/test/LoginSteps.java
  integration-tests/src/test/java/gov/ca/cwds/test/TestCognitoWithMFAMode.java
  integration-tests/src/test/java/gov/ca/cwds/test/TestDevMode.java
Labels: patch

#384 Fit 366 apply smoke testing to perry
  Jenkinsfile-release.groovy
  integration-tests/src/test/java/gov/ca/cwds/test/LoginSteps.java
Labels: patch

#385 FIT-366 Apply the new shared library for smoke testing to Perry
  Jenkinsfile-complete.groovy
  Jenkinsfile-release.groovy
Labels: patch
