Repository ca-cwds/perry, pull requests merged in 2019-02, with the labels that each got.

#324 COG-1098 bug fixed with event user roles
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/NotesChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserAttributeChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRegistrationResentEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: patch

#325 sonar fix
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
Labels: patch

#326 COG-1113: Make changes in Postgres database schema allowing moving users data to this database
  build.gradle
Labels: patch

#323 Cog 1018 perry characters with accents corrupt data
  src/main/java/gov/ca/cwds/service/sso/OAuth2Service.java
  src/main/java/gov/ca/cwds/service/sso/OAuth2Utf8RestTemplate.java
  src/test/java/gov/ca/cwds/service/sso/OAuth2Utf8RestTemplateTest.java
Labels: patch

#327 COG-1180 Roles names instead of Ids in events fixed
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: patch

#328 COG-1197 Refactor code in Events
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/NotesChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/PermissionsChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCreatedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserEnabledStatusChangedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRoleChangedEvent.java
  src/main/java/gov/ca/cwds/idm/service/AuditService.java
  src/main/java/gov/ca/cwds/idm/service/AuditServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/NsUserBuilder.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseDiffMapBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/OtherUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtil.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/BaseDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/CollectionUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/Diff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/EmailUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/RolesUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/StringUserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/UserEnabledStatusAttributeDiff.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/AbstractUserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/CollectionAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/EmailAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/RoleAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/StringAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/UserAttributeDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/diff/builder/UserEnabledStatusDiffBuilder.java
  src/main/java/gov/ca/cwds/idm/service/diff/BooleanDiff.java
  src/main/java/gov/ca/cwds/idm/service/diff/Diff.java
  src/main/java/gov/ca/cwds/idm/service/diff/StringDiff.java
  src/main/java/gov/ca/cwds/idm/service/diff/StringSetDiff.java
  src/main/java/gov/ca/cwds/idm/service/diff/UpdateDifference.java
  src/main/java/gov/ca/cwds/idm/service/execution/OptionalExecution.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationService.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/util/IdToNameConverter.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/NsUserBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/DatabaseDiffMapBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UpdatedAttributesBuilderTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtilTest.java
  src/test/java/gov/ca/cwds/idm/service/diff/DifferencingTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
Labels: minor

#331 naming refactoring done
  src/main/java/gov/ca/cwds/idm/event/EmailChangedEvent.java
Labels: patch

#334 COG-1107 Implement new user creation approach with saving part of the data to Postgres DB
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsUser.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/NsUserService.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/mapper/NsUserMapper.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/java/gov/ca/cwds/idm/service/mapper/NsUserMapperTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
  src/test/java/gov/ca/cwds/idm/util/TestUtils.java
  src/test/resources/fixtures/idm/create-user/delete-fail.json
  src/test/resources/fixtures/idm/create-user/email-fail.json
Labels: minor

#337 COG-1107: Sonar fix
  src/main/java/gov/ca/cwds/idm/service/TransactionalUserService.java
Labels: patch

#338 COG-1118 Implement new user update approach with updating part of the data from Postgres DB
  src/main/java/gov/ca/cwds/idm/service/NsUserBuilder.java
  src/main/java/gov/ca/cwds/idm/service/NsUserServiceImpl.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/NsUserBuilderTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/resources/fixtures/idm/get-user/with-racfid-and-no-phone-extension.json
  src/test/resources/liquibase/ns-data.xml
Labels: minor

#341 FIT-421 Fixed the PR SonarQube issue
  Jenkinsfile-complete.groovy
  Jenkinsfile-pull-request.groovy
Labels: patch

#340 COG-1199 Store events to Postgress
  build.gradle
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/main/java/gov/ca/cwds/idm/event/AuditEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/entity/NsAuditEvent.java
  src/main/java/gov/ca/cwds/idm/persistence/ns/repository/NsAuditEventRepository.java
  src/main/java/gov/ca/cwds/idm/service/AuditEventIndexService.java
  src/main/java/gov/ca/cwds/idm/service/AuditEventService.java
  src/main/java/gov/ca/cwds/idm/service/AuditService.java
  src/main/java/gov/ca/cwds/idm/service/AuditServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/IdmService.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/UserUpdateRequest.java
  src/main/java/gov/ca/cwds/service/dto/CwsUserInfo.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithSearchTest.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationWithUserLogTest.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/ResendInvitationEmailTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/persistence/ns/repository/NsAuditEventRepositoryTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/mapper/NsUserMapperTest.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
  src/test/resources/hibernate.cfg.xml
Labels: minor

#343 Cog 1199aa
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/MappingService.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacade.java
  src/main/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeImpl.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/AttributeHelper.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationService.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/util/Utils.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
  src/test/java/gov/ca/cwds/idm/util/TestHelper.java
  src/test/java/gov/ca/cwds/util/UtilsTest.java
  src/test/resources/fixtures/idm/failed-operations/users-and-operations.json
Labels: patch

#344 COG-1269 FIX: enabled value should be set for user added to the index…
  src/main/java/gov/ca/cwds/idm/service/IdmServiceImpl.java
  src/main/java/gov/ca/cwds/idm/service/UserService.java
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
Labels: patch

#346 COG-1268 DB2 table lock issue
  build.gradle
  config/perry-dev.yml
  config/perry-prod.yml
  src/main/java/gov/ca/cwds/config/CMSConfiguration.java
  src/test/java/gov/ca/cwds/idm/BaseIdmIntegrationTest.java
  src/test/java/gov/ca/cwds/idm/service/IdmServiceImplTest.java
  src/test/java/gov/ca/cwds/util/LiquibaseUtils.java
  src/test/java/gov/ca/cwds/web/PerryDevModeTest.java
  src/test/java/gov/ca/cwds/web/PerryMFALoginTest.java
  src/test/java/gov/ca/cwds/web/StaffPersonHasAssignmentTest.java
Labels: major

#347 perry-clustered-dev yam updated
  config/perry-clustered-dev.yml
Labels: patch

#348 preview template yml updated
  config/perry-preview-template.yml
Labels: major

#350 Cog 1164 unlock user cws cares in detail view
  src/main/java/gov/ca/cwds/idm/IdmResource.java
  src/test/java/gov/ca/cwds/idm/UserLockTest.java
Labels: minor
