Repository ca-cwds/perry, pull requests merged in 2019-05, with the labels that each got.

#392 COG-1152 - admin_name and user_name in audit_event should be in "Last Name, First Name" format for all events
  src/main/java/gov/ca/cwds/idm/event/UserCausedChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: minor

#393 COG-1207 Allow County/Office Admin to Edit Another County/Office Admin
  .gitignore
  src/main/java/gov/ca/cwds/config/api/common/SpApiAccessDeniedHandler.java
  src/main/java/gov/ca/cwds/config/api/common/SpApiAuthenticationErrorHandler.java
  src/main/java/gov/ca/cwds/data/persistence/auth/CmsUserAuthPrivilege.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/AbstractAdminActionsAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizer.java
  src/main/java/gov/ca/cwds/idm/service/role/implementor/StateAdminAuthorizer.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/authorization/AuthorizationServiceImplTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/CountyAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/service/role/implementor/OfficeAdminAuthorizerTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/resources/fixtures/idm/get-user/locked-user.json
  src/test/resources/fixtures/idm/get-user/no-locked-value-unlocked.json
  src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
  src/test/resources/fixtures/idm/get-user/unlocked_user.json
  src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
  src/test/resources/fixtures/idm/update-user/county-admin-updates-county-admin-from-other-county.json
  src/test/resources/fixtures/idm/update-user/county-admin-updates-worker-from-other-county.json
  src/test/resources/fixtures/idm/update-user/county-admin-upgrade-to-county-admin.json
  src/test/resources/fixtures/idm/update-user/office-admin-updates-office-admin-from-other-office.json
  src/test/resources/fixtures/idm/update-user/office-admin-upgrade-to-office-admin.json
  src/test/resources/liquibase/cms-data.xml
  src/test/resources/liquibase/ns-data.xml
Labels: minor

#394 COG-1406 update unlocked status in index
  src/main/java/gov/ca/cwds/idm/lifecycle/UserLockService.java
  src/test/java/gov/ca/cwds/idm/UserLockTest.java
Labels: patch

#395 fix: FIT-583 Rollback in case of failed deploy.
  Jenkinsfile-release.groovy
Labels: patch

#396 COG-1152 - Fix admin_name is not formatted as lastname, firstname
  src/main/java/gov/ca/cwds/idm/event/AdminCausedChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserCausedChangeLogEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserChangeLogEvent.java
  src/main/java/gov/ca/cwds/util/CurrentAuthenticatedUserUtil.java
  src/main/java/gov/ca/cwds/util/UserNameFormatter.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
Labels: patch

#398 COG-1207 add current user's role to the list of possible values
  src/main/java/gov/ca/cwds/idm/service/UserEditDetailsService.java
  src/main/java/gov/ca/cwds/idm/service/filter/MainRoleFilter.java
  src/test/resources/fixtures/idm/get-user/locked-user.json
  src/test/resources/fixtures/idm/get-user/no-locked-value-unlocked.json
  src/test/resources/fixtures/idm/get-user/no-racfid-valid.json
  src/test/resources/fixtures/idm/get-user/unlocked_user.json
  src/test/resources/fixtures/idm/get-user/with-county-admin-id.json
  src/test/resources/fixtures/idm/get-user/with-racfid-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-state-admin-id.json
Labels: patch

#400 COG-1473 Allow Creation & Storage of Cell/Mobil number
  config/idm.groovy
  src/main/java/gov/ca/cwds/idm/dto/User.java
  src/main/java/gov/ca/cwds/idm/dto/UserUpdate.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/StandardUserAttribute.java
  src/main/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtil.java
  src/main/java/gov/ca/cwds/idm/service/cognito/util/CognitoUtils.java
  src/main/java/gov/ca/cwds/idm/service/diff/UpdateDifference.java
  src/main/java/gov/ca/cwds/idm/service/validation/ValidationServiceImpl.java
  src/main/java/gov/ca/cwds/service/messages/MessageCode.java
  src/main/resources/messages/tech_messages.properties
  src/main/resources/messages/user_messages.properties
  src/test/java/gov/ca/cwds/idm/CreateUserTest.java
  src/test/java/gov/ca/cwds/idm/UpdateUserTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/CognitoServiceFacadeTest.java
  src/test/java/gov/ca/cwds/idm/service/cognito/attribute/UserUpdateAttributesUtilTest.java
  src/test/java/gov/ca/cwds/idm/service/diff/UpdateDifferenceTest.java
  src/test/java/gov/ca/cwds/idm/service/validation/ValidationServiceMockTest.java
  src/test/java/gov/ca/cwds/idm/util/TestCognitoServiceFacade.java
  src/test/resources/fixtures/idm/create-user/invalid-cell-phone.json
  src/test/resources/fixtures/idm/failed-operations/failed-operations-valid.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-1.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-2.json
  src/test/resources/fixtures/idm/get-user/with-racfid-and-db-data-valid-3.json
  src/test/resources/fixtures/idm/get-users/all-valid.json
  src/test/resources/fixtures/idm/update-user/invalid-cell-phone-number.json
  src/test/resources/fixtures/idm/users-search/valid.json
Labels: minor

#399 COG-1468 Notification Web Service to Consume Registration Complete event
  src/main/java/gov/ca/cwds/idm/dto/IdmUserNotification.java
  src/main/java/gov/ca/cwds/idm/dto/NotificationType.java
  src/main/java/gov/ca/cwds/idm/event/UserLockedEvent.java
  src/main/java/gov/ca/cwds/idm/event/UserRegistrationCompleteEvent.java
  src/test/java/gov/ca/cwds/idm/IdmNotificationTest.java
  src/test/java/gov/ca/cwds/idm/event/UserChangeLogEventTest.java
  src/test/resources/fixtures/idm/notify/invalid.json
Labels: minor

#401 Make PerryAccount serializable
  api-security-common/src/main/java/gov/ca/cwds/security/realm/PerryAccount.java
Labels: patch

#402 Add serialVersionUID to PerryAccount
  api-security-common/src/main/java/gov/ca/cwds/security/realm/PerryAccount.java
Labels: patch

#403 Fix SecutiryModule class initialization bug
  api-security/src/main/java/gov/ca/cwds/security/module/SecurityModule.java
Labels: bug, patch
